### ISSUE TITLE
Web video player overlay for annotation UI

### ISSUE THREAD

**Issue by trekhopton** [ausocean/openfish#24]
The OpenFish annotation system is intended to be able to create metadata for underwater video content. See issue #1, Video Data Annotator (VDA). 

While a native OpenFish player may be developed in the future, let's initially use 3rd party video players as the base for our VDA, eg. YouTube player, HLS player or Vidgrind MJPEG Player. We can then develop a transparent overlay that matches the player's video resolution and ratio. The user should be able to drag bounding boxes around areas of interest and annotate the observation. The boxes and annotations shown should dynamically change over time as the video plays. The user should also be able to mark start and end times for observations, ie. the time a species appears in the stream and when it disappears from view.

**Comment by scott97** [comment]
Openfish now has an annotation overlay that uses the YouTube player
