### ISSUE TITLE
datastore: Default implementations for Encode/Decode.

### ISSUE THREAD

**Issue by scruzin** [ausocean/openfish#3]
The datastore currently requires clients to implement Encode/Decode methods for each entity.

It is proposed providing default implementations using Go's built-in JSON encoding and decoding. Clients could still override the defaults if required.

**Comment by trekhopton** [comment]
See a discussion about this topic here: https://bitbucket.org/ausocean/vidgrind/issues/300/iotds-create-generic-json-encode-decode .
