### ISSUE TITLE
Create datastore for video stream data

### ISSUE THREAD

**Issue by scott97** [ausocean/openfish#5]

**Comment by Saxon1** [comment]
What exactly does a video stream refer to ? If this is to represent any video, that is something that stored on youtube, something that is currently youtube live broadcasting or something that is in the datastore (or any combination of these) we should have fields with an identifier(s) for each of these things. If for example, you had a youtube url field, you could get this and embed the video in a page (whether it's live or stored) or maybe you only have a datastore identifier, so similarly you can get the video from the datastore and display on page. Or, maybe you have both, in which case you choose where you get the video from depending on the task. For simple playing and annotation, maybe we use the youtube video. Then for more extreme object detection and machine learning tasks, we get it from the datastore.
